### PR TITLE
refactor(linter): adding more linter rules

### PR DESCRIPTION
**Pull request by tcoratger**
In order to secure the implementations and the code as a whole, this PR reinforces the linter requirements based on the linter file contained in the following `eslint-config-standard` repo: https://github.com/standard/eslint-config -standard/tree/master.

This PR also fixes the problems that appeared with these new rules as best as possible.

When the problem requires further investigation (only a few cases), the correction of the problem is left for a later PR. In this specific case, this PR simply deactivates the linter for the line in question.

Additionally, this PR also contains an upgrade to the formatting of all the files thanks to the `prettier:write` command which allows the developer to format all the code files via a single command line.

### CODE REVIEW

**Comment by SAPikachu** [comment]
I don't really agree with this PR, `standard` introduces too many styling rules which I consider ugly (no semicolon) or make code harder to edit ([comma-style](http://eslint.org/docs/rules/comma-style)). If there are useful rules we can add them individually.

Also FWIW, for typescript projects, `eslint-config-standard-with-typescript` should be used instead of `standard`.

**Comment by tcoratger** [comment]
@SAPikachu Maybe we can update the`.eslintrc.json` file to put back the old rules but I think that the PR only bring useful rules (at least from my point of view):
- I removed the rule concerning semicolon so we have no error on this this.
- Unused variables.
- Necessary spacing between functions for a class.
- Several redundant imports in the same file
- Obligation to return in a findIndex or a map if {}
- Global formatting to respect the prettier file.
- ...

If you don't agree, we can simply close this PR :). But what I propose is that we keep the changes and put the old rules back in the linter if you want (even if the new rules don't seem to disturb that much since there are no errors on CI on the PR). WDT?

**Comment by SAPikachu** [comment]
Well if we remove the `standard` extend and rules related to styling (semicolon, comma position, new lines between blocks etc) and fix issues related to TS (like: `no-redeclare` should be replaced with `@typescript-eslint/no-redeclare`, see https://typescript-eslint.io/rules/#extension-rules ), I can accept it. :)

**Comment by tcoratger** [comment]
@SAPikachu With the last push:
- Standard extend is removed
- No rule for semicolon
- Old rules for comma
- `lines-between-class-members` seems good to be because it helps to air out the code inside a class
- Basic typescript specific rules are set:
```json
"@typescript-eslint/explicit-function-return-type": "off",
    "@typescript-eslint/no-unused-vars": ["warn", { "argsIgnorePattern": "^_" }],
    "@typescript-eslint/no-redeclare": ["error"],
```
If needed, we can complement these rules over time :)

**Comment by SAPikachu** [comment]
Thanks! Looks mostly good to me. One more suggestion: there are quite a few `// eslint-disable-next-line no-redeclare` and similar lines added, but they should no longer be needed after the rules are fixed, can you remove these lines? After that I can merge this. :)

**Comment by tcoratger** [comment]
> Thanks! Looks mostly good to me. One more suggestion: there are quite a few `// eslint-disable-next-line no-redeclare` and similar lines added, but they should no longer be needed after the rules are fixed, can you remove these lines? After that I can merge this. :)

@SAPikachu Done :)

**Review by SAPikachu — APPROVED** [review]
Thanks!

**Pull request merged**
